DROP DATABASE  IF EXISTS Tateti;
CREATE DATABASE IF NOT EXISTS Tateti;
USE Tateti;
CREATE TABLE users(id INT NOT NULL AUTO_INCREMENT,
    names VARCHAR(30) NOT NULL,
    points INT(10) NOT NULL,
    PRIMARY KEY(id));